{% set name = "pytorch_metric_learning" %}
{% set version = "0.9.57" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "c6394e6b824cc3f46a1c36934b5d420ec630b35720c510e3ce5076a787d34634"

build:
  number: 0
  script: "python -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
  run:
    - python >=3.0
    - numpy
    - scikit-learn
    - tqdm
    - pytorch
    - torchvision

about:
  home: "https://github.com/KevinMusgrave/pytorch_metric_learning"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "The easiest way to use metric learning in your application. Modular, flexible, and extensible. Written in PyTorch."
  doc_url: "https://kevinmusgrave.github.io/pytorch_metric_learning"
  dev_url: ""

extra:
  recipe-maintainers:
    - KevinMusgrave
